"use client";

import {useEffect, useMemo, useRef, useState} from "react";
import QRCode from "qrcode";

export type ConnectMode = "extension" | "qr";

type Wallet = {
    id: string;
    name: string;
    label: string;
    color: string;
    category: "extension" | "mobile";
    deepLink?: (uri: string) => string;
};

const WALLETS: Wallet[] = [
    {
        id: "metamask-ext",
        name: "MetaMask (Extension)",
        label: "MM",
        color: "#F6851B",
        category: "extension",
    },
    {
        id: "metamask",
        name: "MetaMask Mobile",
        label: "MM",
        color: "#F6851B",
        category: "mobile",
        deepLink: (uri) => `https://metamask.app.link/wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: "trust",
        name: "Trust Wallet",
        label: "TW",
        color: "#3375BB",
        category: "mobile",
        deepLink: (uri) => `https://link.trustwallet.com/wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: "rainbow",
        name: "Rainbow",
        label: "RB",
        color: "#001E59",
        category: "mobile",
        deepLink: (uri) => `https://rnbwapp.com/wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: "coinbase",
        name: "Coinbase Wallet",
        label: "CB",
        color: "#0052FF",
        category: "mobile",
        deepLink: (uri) =>
            `https://go.cb-w.com/wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: "okx",
        name: "OKX Wallet",
        label: "OK",
        color: "#000000",
        category: "mobile",
        deepLink: (uri) =>
            `okx://wallet/wc?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: "phantom",
        name: "Phantom",
        label: "PH",
        color: "#AB9FF2",
        category: "mobile",
        deepLink: (uri) => `https://phantom.app/ul/v1/connect?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: "argent",
        name: "Argent",
        label: "AR",
        color: "#FF875B",
        category: "mobile",
        deepLink: (uri) => `https://argent.link/app?uri=${encodeURIComponent(uri)}`,
    },
    {
        id: "zerion",
        name: "Zerion",
        label: "ZR",
        color: "#2962EF",
        category: "mobile",
        deepLink: (uri) => `https://wallet.zerion.io/wc?uri=${encodeURIComponent(uri)}`,
    },
];

type Props = {
    isOpen: boolean;
    onClose: () => void;
    /** Generated by wagmi’s walletConnect provider via `display_uri`. */
    wcUri: string | null;
    /** Called when user wants to connect via injected (MetaMask extension). */
    onPickExtension: () => void;
    /** Called when the user picks a mobile wallet — should trigger WC `connect`. */
    onStartWalletConnect: () => void;
};

export function WalletPickerModal({isOpen, onClose, wcUri, onPickExtension, onStartWalletConnect}: Props) {
    const [query, setQuery] = useState("");
    const [selectedWallet, setSelectedWallet] = useState<Wallet | null>(null);
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const [copied, setCopied] = useState(false);

    const filtered = useMemo(
        () => WALLETS.filter((w) => w.name.toLowerCase().includes(query.toLowerCase())),
        [query]
    );
    const extensions = filtered.filter((w) => w.category === "extension");
    const mobiles = filtered.filter((w) => w.category === "mobile");

    // Render QR when uri + selected mobile wallet
    useEffect(() => {
        if (!wcUri || !selectedWallet || !canvasRef.current) return;
        QRCode.toCanvas(canvasRef.current, wcUri, {
            width: 256,
            margin: 1,
            color: {dark: "#18181b", light: "#ffffff"},
            errorCorrectionLevel: "H",
        });
    }, [wcUri, selectedWallet]);

    // Reset state when modal closes or session connects
    useEffect(() => {
        if (!isOpen) {
            setSelectedWallet(null);
            setQuery("");
        }
    }, [isOpen]);

    useEffect(() => {
        if (!copied) return;
        const t = setTimeout(() => setCopied(false), 1500);
        return () => clearTimeout(t);
    }, [copied]);

    if (!isOpen) return null;

    const inQrView = selectedWallet?.category === "mobile";

    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-zinc-900/40 backdrop-blur-sm p-4"
            onClick={onClose}
        >
            <div
                className="pop-in flex w-full max-w-md flex-col rounded-2xl border border-zinc-200 bg-white shadow-bento-lg"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Header */}
                <div className="relative flex items-center justify-center border-b border-zinc-100 px-6 py-4">
                    {inQrView && (
                        <button
                            onClick={() => setSelectedWallet(null)}
                            className="absolute left-3 rounded-md p-1 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-700"
                            aria-label="Back"
                        >
                            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <polyline points="15 18 9 12 15 6" />
                            </svg>
                        </button>
                    )}
                    <h3 className="text-base font-semibold text-zinc-900">
                        {inQrView ? `Connect ${selectedWallet.name}` : "Connect Wallet"}
                    </h3>
                    <button
                        onClick={onClose}
                        className="absolute right-3 rounded-md p-1 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-700"
                        aria-label="Close"
                    >
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M6 6l12 12M18 6l-12 12" />
                        </svg>
                    </button>
                </div>

                {!inQrView && (
                    <>
                        {/* Search */}
                        <div className="border-b border-zinc-100 p-4">
                            <div className="relative">
                                <svg
                                    className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400"
                                    width="16"
                                    height="16"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth="2"
                                >
                                    <circle cx="11" cy="11" r="7" />
                                    <line x1="21" y1="21" x2="16.65" y2="16.65" />
                                </svg>
                                <input
                                    autoFocus
                                    value={query}
                                    onChange={(e) => setQuery(e.target.value)}
                                    placeholder="Search wallets…"
                                    className="w-full rounded-lg border border-zinc-200 bg-white py-2 pl-9 pr-3 text-sm focus:border-cb-500 focus:outline-none focus:ring-2 focus:ring-cb-100"
                                />
                            </div>
                        </div>

                        {/* Wallet list */}
                        <div className="max-h-[400px] overflow-y-auto p-3">
                            {extensions.length > 0 && (
                                <div>
                                    <div className="px-2 pb-2 pt-1 text-[10px] font-semibold uppercase tracking-wider text-zinc-500">
                                        Browser extension
                                    </div>
                                    {extensions.map((w) => (
                                        <WalletRow
                                            key={w.id}
                                            wallet={w}
                                            onClick={() => {
                                                onPickExtension();
                                                onClose();
                                            }}
                                        />
                                    ))}
                                </div>
                            )}

                            {mobiles.length > 0 && (
                                <div className="mt-2">
                                    <div className="px-2 pb-2 pt-1 text-[10px] font-semibold uppercase tracking-wider text-zinc-500">
                                        Mobile wallets · scan QR
                                    </div>
                                    {mobiles.map((w) => (
                                        <WalletRow
                                            key={w.id}
                                            wallet={w}
                                            onClick={() => {
                                                setSelectedWallet(w);
                                                onStartWalletConnect();
                                            }}
                                        />
                                    ))}
                                </div>
                            )}

                            {filtered.length === 0 && (
                                <div className="p-6 text-center text-sm text-zinc-500">
                                    No wallets match “{query}”. Try a different search.
                                </div>
                            )}
                        </div>

                        <div className="border-t border-zinc-100 px-6 py-3 text-center text-[11px] text-zinc-400">
                            Powered by WalletConnect · Sepolia testnet
                        </div>
                    </>
                )}

                {inQrView && (
                    <div className="p-6">
                        {wcUri ? (
                            <>
                                <p className="text-center text-sm text-zinc-600">
                                    Open <span className="font-semibold">{selectedWallet.name}</span> on your phone and scan this code.
                                </p>

                                <div className="mt-5 flex justify-center">
                                    <div className="relative flex items-center justify-center rounded-2xl bg-white p-3 ring-1 ring-zinc-200">
                                        <canvas ref={canvasRef} className="rounded-md" />
                                        <div
                                            className="pointer-events-none absolute flex h-12 w-12 items-center justify-center rounded-xl ring-2 ring-white"
                                            style={{backgroundColor: selectedWallet.color}}
                                        >
                                            <span className="text-xs font-bold text-white">{selectedWallet.label}</span>
                                        </div>
                                    </div>
                                </div>

                                <div className="mt-5 flex flex-col gap-2">
                                    {selectedWallet.deepLink && (
                                        <a
                                            href={selectedWallet.deepLink(wcUri)}
                                            target="_blank"
                                            rel="noreferrer"
                                            className="block w-full rounded-lg bg-cb-600 px-3 py-2 text-center text-sm font-semibold text-white transition hover:bg-cb-700"
                                        >
                                            Open in {selectedWallet.name}
                                        </a>
                                    )}
                                    <button
                                        onClick={async () => {
                                            if (!wcUri) return;
                                            await navigator.clipboard.writeText(wcUri);
                                            setCopied(true);
                                        }}
                                        className="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm font-medium text-zinc-700 transition hover:bg-zinc-50"
                                    >
                                        {copied ? "Copied!" : "Copy WalletConnect URI"}
                                    </button>
                                </div>
                            </>
                        ) : (
                            <div className="flex items-center justify-center py-12 text-sm text-zinc-500">
                                <span className="mr-2 inline-block h-3 w-3 animate-pulse rounded-full bg-cb-500" />
                                Generating QR code…
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}

function WalletRow({wallet, onClick}: {wallet: Wallet; onClick: () => void}) {
    return (
        <button
            onClick={onClick}
            className="flex w-full items-center justify-between gap-3 rounded-xl px-3 py-2.5 text-left transition hover:bg-zinc-50"
        >
            <div className="flex items-center gap-3">
                <div
                    className="flex h-9 w-9 items-center justify-center rounded-xl ring-1 ring-zinc-200"
                    style={{backgroundColor: wallet.color}}
                >
                    <span className="text-xs font-bold text-white">{wallet.label}</span>
                </div>
                <div>
                    <div className="text-sm font-semibold text-zinc-900">{wallet.name}</div>
                    <div className="text-[11px] text-zinc-500">
                        {wallet.category === "extension" ? "Browser extension" : "Scan QR with phone"}
                    </div>
                </div>
            </div>
            <span className="text-zinc-400">→</span>
        </button>
    );
}
